#!/usr/bin/env python
import sys
d = set(open(sys.argv[1]).read().split('\n'))
import re
contents = sys.stdin.read()
sys.stdout.write(re.sub(r'[^ \n]+', lambda m: '<'+m.group()+'>' if m.group().lower() not in d else m.group(), contents))
